<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW0060" ignored="1" name="SecondTest" tests="6" failures="2" timestamp="16 Mar 2018 09:14:18 GMT" time="0.005" errors="0">
  <testcase name="testPow" time="0.0" classname="com.epam.test.calculator.NegativTests"/>
  <testcase name="testSin" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.epam.test.calculator.NegativTests.testSin(NegativTests.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testSin -->
  <testcase name="testSinNeg" time="0.001" classname="com.epam.test.calculator.NegativTests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.epam.test.calculator.NegativTests.testSinNeg(NegativTests.java:30)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testSinNeg -->
  <testcase name="testTg" time="0.001" classname="com.epam.test.calculator.NegativTests"/>
  <testcase name="testCos" time="0.0" classname="com.epam.test.calculator.NegativTests"/>
  <testcase name="testCtg" time="0.0" classname="com.epam.test.calculator.NegativTests"/>
  <testcase name="testCosn" time="0.0" classname="com.epam.test.calculator.NegativTests">
    <ignored/>
  </testcase> <!-- testCosn -->
</testsuite> <!-- SecondTest -->
